name: Releases

on: 
  push:
    branches:
      - 'main'

jobs:

  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Get next version
      uses: reecetech/version-increment@2023.3.1
      id: version
      with:
        scheme: semver
        increment: patch
        
    - uses: ncipollo/release-action@v1
      with:
        tag: 'v${{ steps.version.outputs.version }}'
        commit: 'main'
        artifacts: "v{{ steps.version.outputs.version }}.tar.gz,v{{ steps.version.outputs.version }}.zip"
        
